GET http://localhost:3000/quotes

###
GET http://localhost:3000/quotes/6a57d78d78c28190ab9cd239

###

GET http://localhost:3000/quotes/6a57d78d78c28190ab9cd239

###

POST http://localhost:3000/quotes
Content-Type: application/json

{
   "quoteAuthor": "Rene Descartes",
   "quoteText": "I think, therefore I am."
}

###

DELETE http://localhost:3000/quotes/6a57d78d78c28190ab9cd239

###

PATCH http://localhost:3000/quotes/6a58589736425ac2269c4a22
Content-Type: application/json

{
    "quoteAuthor": "Rene Deloop",
    "quoteText": "I do think, and because of that, I am."
}