GET http://localhost:3000/quotes

###
GET http://localhost:3000/quotes/6a57d78d78c28190ab9cd239

###

GET https://quote-api-2p0h.onrender.com/quotes

###

GET http://localhost:3000/quotes/6a57d78d78c28190ab9cd239

###

POST http://localhost:3000/quotes
Content-Type: application/json
X-API-KEY: NEWquoteKey200

{
   "author": "leviz1400",
   "text": "Here's to a new day!"
}

###

POST https://quote-api-2p0h.onrender.com/quotes
Content-Type: application/json
X-API-KEY: NEWquoteKey200

{
    "author": "leviz1400",
    "text": "Hello, Render!"
}

###

DELETE http://localhost:3000/quotes/6a58589736425ac2269c4a22

###

PATCH http://localhost:3000/quotes/6a59543f79941e4c50d867b7
Content-Type: application/json

{
    "author": "Rene Deloop",
    "text": "I do think, and because of that, I am."
}